### ISSUE TITLE
socket or signal server 

### ISSUE THREAD

**Issue by webleb** [muaz-khan/RTCMultiConnection-Server#10]
Hello
i want the socket server which was working on https://webrtcweb.com:9001
if someone can help 
it is old version

**Comment by muaz-khan** [comment]
server.js => https://github.com/muaz-khan/RTCMultiConnection/blob/724ead7cbb589a772b8bb41abd22acff3f700a5d/server.js

Signaling-Server.js => https://github.com/muaz-khan/RTCMultiConnection/blob/724ead7cbb589a772b8bb41abd22acff3f700a5d/Signaling-Server.js

Scalable-Broadcast.js => https://github.com/muaz-khan/RTCMultiConnection/blob/724ead7cbb589a772b8bb41abd22acff3f700a5d/Scalable-Broadcast.js

Put all 3 files into a directory. And run `node server.js`. (after installing NPM packages)

**Comment by webleb** [comment]
Hi Muaz
 i did all what you mention and it was working perfect but now again  i have problem with socket server and nothing it is changed from my end , when i refresh browser i cant re-enter in video call with others till they refresh too , and sometimes the connection is lost between user and video call is stopped or frozen  in some users  
please advice 
i have install socket server in my own server and everything was working good and nothing is changed in my end 
Thanks
