### ISSUE TITLE
Website Unreachable

### ISSUE THREAD

**Issue by Careprod-Technologies** [muaz-khan/RTCMultiConnection-Server#35]
Hello dear community,

Hope I can find some help there. I'm actually working on a solution for internal tchat and this project seems to perfectly suits.
I did some research and worked a lot about my solution, but I'm actually facing a problem.

In fact, I did host my app on AWS Amplify and works fine (have interactions, tchat, share files, etc... while i used it on localhost and when I hosted the node server of @muaz-khan  on heroku). But now I wanna have my server on AWS EC2, so I followed instructions (create a ec2 instances, create elastic ip for the instance, buy a domain name and clone my server on the ubuntu virtual machine , create certificates..) But when it arrives at the certificates, I have many problems. 

Currently i'm lauching my node server correctly but I have problem with SSL and I'm not really attracted by network and stuff like that... I keep getting this error : ERR_SSL_VERSION_OR_CIPHER_MISMATCH

I did some research but... I'm not you know.. the type of guy that is really the job, so i'll be glad if I can find some help

I'm also dropping you my server code in order to have some review if I also did something wrong 

Best Regards,

Sam

![Capture d’écran 2021-07-16 à 17 00 29](https://user-images.githubusercontent.com/82519761/125969963-9fd8a20f-d838-4b0f-9fbc-a7e861925026.png)
![Capture d’écran 2021-07-16 à 17 00 46](https://user-images.githubusercontent.com/82519761/125969968-f36ce957-41a5-42a4-b27e-9ed82d796206.png)
![Capture d’écran 2021-07-16 à 17 01 07](https://user-images.githubusercontent.com/82519761/125969972-06715362-62ae-43fb-99df-5127b37cf679.png)
![Capture d’écran 2021-07-16 à 17 01 35](https://user-images.githubusercontent.com/82519761/125969974-1da1ba9c-6ade-4f27-a74f-71320cdfc4bc.png)
![Capture d’écran 2021-07-16 à 17 01 58](https://user-images.githubusercontent.com/82519761/125969975-bda1cd1a-63b2-48dc-949b-d8ae11a45f8e.png)
![Capture d’écran 2021-07-16 à 17 02 12](https://user-images.githubusercontent.com/82519761/125969977-1bb7df58-a419-4301-8e55-00694d0a4202.png)
![Capture d’écran 2021-07-16 à 17 02 20](https://user-images.githubusercontent.com/82519761/125969979-ea12f4bc-680f-4cdc-9b4e-bce66a243894.png)
![Capture d’écran 2021-07-16 à 17 02 31](https://user-images.githubusercontent.com/82519761/125969981-06208c83-e52e-4cde-baf3-3d67c00a41bf.png)

**Comment by Careprod-Technologies** [comment]
The back end developer working with me that recently join our team manage to host it on azure so everything is ok.

I thank you a lot ,

Kind Regards , Sam

**Comment by arunkumartdr** [comment]
can anyone help to host this on AWS Lightsail Nodejs Server
